package com.sbu.services;

import com.sbu.controller.CustomerController;
import com.sbu.data.AccountRepository;
import com.sbu.data.CustomerRepository;
import com.sbu.data.entitys.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import javax.ws.rs.core.Response;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Set;

import static com.sbu.services.ResponseUtil.build200;

/**
 * Not implmented:
 Customer:

 */
@CrossOrigin
@RestController
@RequestMapping("/storage/customer")
public class CustomerService extends StorageService  {

// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private CustomerRepository customerRepository;


    @Autowired
    private CustomerController customerController;

    @Autowired
    private AccountRepository accountRepository;

    @GetMapping(path="/all")
    public @ResponseBody
    Iterable<Account> getAllUsers() {
        // This returns a JSON or XML with the users
        return accountRepository.findAll();
    }


    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/moviesById/{customerID}", method= RequestMethod.GET)
    public Response getCustomerMoviesByID(@PathVariable("customerID") String customerID) throws IOException {
        Set<Movie> info = customerController.getCustomerMoviesById(customerID);
        return build200(info);
    }

    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/moviesByType/{type}", method= RequestMethod.GET)
    public Response getMoviesByType(@PathVariable("type") String type) throws IOException {
        Iterable<Movie> movies = customerController.getMoviesByType(type);
        return build200(movies);
    }



    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/queue/{customerID}", method= RequestMethod.GET)
    public Response getCustomerQueueByID(@PathVariable("customerID") String customerID) throws IOException {
        Iterable<Movie> movies= customerController.getCustomerQueueById(customerID);
        return build200(movies);
    }

    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/account/{customerID}", method= RequestMethod.GET)
    public Response getCustomerAccountByID(@PathVariable("customerID") String customerID) throws IOException {
        Account info = customerController.getCustomerAccountById(customerID);
        return build200(info);
    }

    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/orders/{customerID}/current", method= RequestMethod.GET)
    public Response getCustomerOrdersByID(@PathVariable("customerID") String customerID) throws IOException {
        Set<Order> info = customerController.getCustomerOrdersById(customerID);
        return build200(info);
    }


    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/bestSellers", method = RequestMethod.GET)
    public Response getBestSellers() throws Exception {
        Set<Movie> res = customerController.getMoviesBestSellers();
        return build200(res);

    }

    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/moviesByKeywords", method = RequestMethod.GET)
    public Response getMovieByKeyword(@RequestParam(value = "csvStringOfKeywords", required = false) String csvStringOfKeywords) throws Exception {
        List<String> keywordItems = Arrays.asList(csvStringOfKeywords.split("\\s*,\\s*"));
        Iterable<Movie> res = customerController.getMoviesByKeywords(keywordItems);
        return build200(res);

    }
    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/moviesByActors", method = RequestMethod.GET)
    public Response getMovieByActor(@RequestParam(value = "csvStringOfActors", required = false) String csvStringOfActors) throws Exception {
        List<String> actors = Arrays.asList(csvStringOfActors.split("\\s*,\\s*"));
        Set<Movie> res = customerController.getMoviesByActors(actors);
        return build200(res);

    }


    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/suggestionMovies/{customerID}", method = RequestMethod.GET)
    public Response getSuggestionsById(@PathVariable("customerID") String customerID) throws Exception {
        Set<Movie> res = customerController.getSuggestions(customerID);
        return build200(res);

    }

    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value = "/{movieID}", method = RequestMethod.POST)
    public Response postRating(@PathVariable("movieID") String movieID,
                               @RequestParam("rating") int rating)throws Exception {
        customerController.postRating(movieID,rating);
        return build200("OK");

    }

    @ResponseStatus(HttpStatus.OK)
    @RequestMapping(value ="/currentlyHeldMovies/{customerID}", method= RequestMethod.GET)
    public Response getHeldMovies(@PathVariable("customerID") String customerID) {
        Set<Movie> res = customerController.getHeldMovies(customerID);
        return build200(res);
    }



}
